### PR TITLE
Performance warnings on spotbugs 

### PR DESCRIPTION
**Pull request by bmscomp**
This pull request targets fixing performance warnings reported by spotbugs

### CODE REVIEW

**Review by bmTas — COMMENTED** [review]
In **BinTextReader**
    **delitmiier** is miss translated to **misdeliver** should be **delimiter**

**Review by bmTas — COMMENTED** [review]
ItemJRec:
   Should be done differently. We know exactly how many child items we have at the when an item is created. I will update the class

In **BinTextReader**
**delitmiier** is mistranslated to **misdeliver** it should be **delimiter**

**Comment by bmTas** [comment]
One more

JRecordConstantVars:
    Needs to remain class (or be removed). It was created because some
JVM scripting languages (e.g. java script) could no access java interfaces, only class variables.
This class was created to provide access to the Record Constants via a normal class variables.

Most of the JVM scripting languages seem to be dying so it might not be needed.

**Comment by bmscomp** [comment]
@bmTas  Pull request updated I restored the class

**Review by bmTas — APPROVED** [review]

**Review by bmTas — APPROVED** [review]

**Review by bmTas — APPROVED** [review]

**Review by bmTas — APPROVED** [review]

**Pull request merged**
